### ISSUE TITLE
dompdf font cache directory

### ISSUE THREAD

**Issue by szepeviktor** [laravel/cashier-braintree#60]
I've noticed that [unset font cache](https://github.com/dompdf/dompdf/blob/master/lib/Cpdf.php#L198-L205) produces PHP files in /vendor/dompdf/dompdf/lib/fonts/

Could you set a Laravel-comform location?

**Comment by driesvints** [comment]
I'm not really sure how this affects Cashier? What's the problem exactly?

**Comment by szepeviktor** [comment]
Thank you for your response.

> What's the problem exactly?

.php files are created under /vendor - which is considered read-only after deploy.

**Comment by driesvints** [comment]
Since this seems to be the default behavior for dompdf I don't think this is an actual issue. You can set the font cache with an option to the `Dompdf` class but since we don't that by default and no one has complained about this so far I don't believe this is a bug.

https://github.com/laravel/cashier-braintree/blob/2.0/src/Invoice.php#L239

Can you perhaps open an issue with them to ask if this default behavior is wanted? For me personally I don't see any issue here.
